---
- name: "Process: {{ mode }} - Downloading SQL dump backups from S3 bucket"
  amazon.aws.aws_s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    #s3_url: "{{ s3_url }}"
    bucket: "{{ aws_bucket }}"
    mode: get
    object: "{{ rancher_db | basename}}"
    dest: "{{ rancher_db }}"
  when: storage == "s3"

- name: "Restoring Rancher SQL data from {{ rancher_db }}"
  shell:
    cmd: |
      cd {{ rancher_path }}
      docker-compose stop rancher-server
      cat {{ rancher_db }} | docker exec -i {{ racher_sql_container_name }} \
        mysql -u {{ rancher_backup_user }} -p{{ rancher_backup_user_pass }} {{ rancher_db_name }}
      docker-compose down
      docker-compose up -d

- name: "Process: {{ mode }} - Remove local copies of the Rancher SQL backup."
  file:
    path: "{{ rancher_db }}"
    state: absent
  when: storage != "local"
